const gulp = require('gulp');
const electronMocha = require('gulp-electron-mocha').default;

gulp.task('test', () =>
	gulp.src('./app/specs.js.autogenerated', {
		read: false
	})
	.pipe(electronMocha({
		electronMocha: {
			renderer: true,
			compilers: 'js:babel-core/register',
			require: 'source-map-support/register',
			env: 'test',
		},
	}))
);
